// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDySy7zsrg4-8ZoKxqUd1GiO2lumOPr_U4',
    appId: '1:794797197167:web:cc3c123301cf16f573ca9a',
    messagingSenderId: '794797197167',
    projectId: 'mi-trabajo-c8b17',
    authDomain: 'mi-trabajo-c8b17.firebaseapp.com',
    storageBucket: 'mi-trabajo-c8b17.appspot.com',
    measurementId: 'G-TDELZLVDN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNNb_AkTKpD3lVyKeRWtfyK0BFy9sT6o',
    appId: '1:794797197167:android:14e4e83cf2c6ad8973ca9a',
    messagingSenderId: '794797197167',
    projectId: 'mi-trabajo-c8b17',
    storageBucket: 'mi-trabajo-c8b17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQMCjlN68w8UyRb4m8A0g6pqk9mrIscp4',
    appId: '1:794797197167:ios:5afd2becad9ffad473ca9a',
    messagingSenderId: '794797197167',
    projectId: 'mi-trabajo-c8b17',
    storageBucket: 'mi-trabajo-c8b17.appspot.com',
    androidClientId: '794797197167-geh439pfd7m3qm63o3e0bs7oof2jkrlb.apps.googleusercontent.com',
    iosClientId: '794797197167-55jmm4rjpkci91tamoq7s8ef6cecd9tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.miTrabajo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQMCjlN68w8UyRb4m8A0g6pqk9mrIscp4',
    appId: '1:794797197167:ios:8b7470a84153a90073ca9a',
    messagingSenderId: '794797197167',
    projectId: 'mi-trabajo-c8b17',
    storageBucket: 'mi-trabajo-c8b17.appspot.com',
    androidClientId: '794797197167-geh439pfd7m3qm63o3e0bs7oof2jkrlb.apps.googleusercontent.com',
    iosClientId: '794797197167-unjpvrrajr6tp2nb60mrj9mfj82g2gfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.miTrabajo.RunnerTests',
  );
}
